import type { NextPage } from "next";
import Head from "next/head";
import BannerSection from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/Hero";
import InfoSection from "../components/Info";
import PackagesSection from "../components/Packages";
import SmallCardsSection from "../components/SmallCards";
import TableSection from "../components/Table";
import VideoSection from "../components/Video";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HeroSection />
        <BannerSection />
        <PackagesSection />
        <VideoSection />
        <TableSection />
        <InfoSection />
        <SmallCardsSection />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
