import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Packages from "../components/Packages";
import TableSection from "../components/Table";
import VideoSection from "../components/Video";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Banner />
        <Packages />
        <VideoSection />
        <TableSection />
      </main>
    </div>
  );
};

export default Home;
